locales:
  en:
    name: Low German Keyboards
    description: >-
      Mobile OS keyboards for the Low German language from the Divvun group at
      UiT.
  nb:
    name: Low German tastatur
    description: Mobiltastatur for Low German fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
